"""add birds table

Revision ID: a08a989c893d
Revises: 0002_add_password_hash
Create Date: 2026-06-03 15:54:02.451645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a08a989c893d'
down_revision: Union[str, Sequence[str], None] = '0002_add_password_hash'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'passwords', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'passwords', type_='unique')
    # ### end Alembic commands ###
